services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.frontend
    command: ng serve --host 0.0.0.0
    volumes:
      # - ./app:/app
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_vrs
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data:
