# Generated by Django 5.2.6 on 2025-09-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seed_vehicle_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="hold_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
